baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[module]
  [module.hugoVersion]
    min = "0.110.0"

[params]
  # Add your theme-specific parameters here

  [params.assets]
  customCSS = ["css/custom.css"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON", "MP3"]

[[outputs.MP3]]
  content_type = "audio/mpeg"
  media_types = ["mp3"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about-me/"
    weight = 10
  [[menu.main]]
    identifier = "experience-projects"
    name = "Experience / Projects"
    url = "/projects/"
    weight = 20
